name: gzdoom
base: core22
version: '4.10.0'
summary: Doom Source Port
description: |
  Snap build from https://github.com/Hvassaa/gzdoom-snap
  To setup WADs, run the app once and put them in ~/snap/gzdoom/current/.config/gzdoom/
  ZDoom is a family of enhanced ports of the Doom engine for running on modern operating systems.
  It runs on Windows, Linux, and OS X, and adds new features not found in the games as originally
  published by id Software.
license: "GPL-3.0"
source-code: "https://github.com/ZDoom/gzdoom"
grade: stable
confinement: strict

apps:
  gzdoom:
    command: bin/desktop-launch $SNAP/usr/local/bin/gzdoom
    plugs:
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - audio-playback
    environment:
      KDE_FULL_SESSION: "false"

layout:
  /usr/local/share/games/doom:
    bind: $SNAP/usr/local/share/games/doom

parts:
  gzdoom:
    source: https://github.com/coelckers/gzdoom.git
    source-tag: 'g4.10.0'
    override-pull: |
      snapcraftctl pull
      patch $SNAPCRAFT_PART_SRC/src/d_iwad.cpp < $SNAPCRAFT_PROJECT_DIR/snap/local/location.patch # change "wad not found" path description
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DNO_FMOD=ON
      - -DZMUSIC_INCLUDE_DIR=$SNAPCRAFT_STAGE/usr/include
      - -DZMUSIC_LIBRARIES=$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libzmusic.so
    build-packages:
      - g++
      - libsdl2-dev
      - zlib1g-dev
      - libbz2-dev
      - libjpeg-dev
      - libfluidsynth-dev
      - libgme-dev
      - libopenal-dev
      - libmpg123-dev
      - libsndfile1-dev
      - libgtk-3-dev
      - timidity
      - nasm
      - libgl1-mesa-dev
      - tar
      - libsdl1.2-dev
      - libglew-dev
      - libvpx-dev
      # trying to fix xcb related errors
      - libxcb1-dev
      - libx11-xcb-dev
      - libxcb-glx0-dev
    stage-packages:
      - libasound2
      - libasyncns0
      - libflac8
      - libgomp1
      - libjpeg-turbo8
      - libogg0
      - libpulse0
      - libsdl2-2.0-0
      - libsndfile1
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1
      - libxxf86vm1
      - libvpx7
      - libgl1 # not detected by snapcraft
      - libopenal1 # not detected by snapcraft
      # It seems these are needed for graphical wad selector
      - kdialog
      - gxmessage
      # trying to fix xcb related erros here
      - xcb # not detected by snapcraft
      - libxcb1
      - libx11-xcb1
      - libxcb-glx0
    after:
      - zmusic
      - desktop-glib-only 
  zmusic:
    source: https://github.com/coelckers/ZMusic.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - g++
    stage-packages:
      - libasound2
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
