name: gzdoom
base: core18
version: 'g4.3.2'
summary: Doom Source Port
description: |
  Snap build from https://github.com/Hvassaa/gzdoom-snap
  To setup WADs, run the app once and put them in ~/snap/gzdoom/current/.config/gzdoom
  ZDoom is a family of enhanced ports of the Doom engine for running on modern operating systems.
  It runs on Windows, Linux, and OS X, and adds new features not found in the games as originally
  published by id Software.
icon: snap/gui/gzdoom.png
license: "GPL-3.0"

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  gzdoom:
    command: desktop-launch $SNAP/bin/gzdoom
    plugs: [desktop, desktop-legacy, unity7, network, opengl, pulseaudio, audio-playback, joystick, x11, wayland, home]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/pulseaudio:$LD_LIBRARY_PATH

parts:
  gzdoom:
    source: https://github.com/coelckers/gzdoom.git
    source-tag: 'g4.3.2'
    plugin: cmake
    configflags: ["-DCMAKE_BUILD_TYPE=Release", "-DNO_FMOD=ON"]
    build-packages:
      - g++
      - make
      - cmake
      - libsdl2-dev
      - git
      - zlib1g-dev
      - libbz2-dev
      - libjpeg-dev
      - libfluidsynth-dev
      - libgme-dev
      - libopenal-dev
      - libmpg123-dev
      - libsndfile1-dev
      - libgtk-3-dev
      - timidity
      - nasm
      - libgl1-mesa-dev
      - tar
      - libsdl1.2-dev
      - libglew-dev
    stage-packages:
      - libsdl2-2.0-0
      - libopenal1
      - libfluidsynth1
      - libgme0
      - libmpg123-0
      - libsndfile1
      - libwildmidi2
      - libgtk-3-0
      - timidity
      - libsdl1.2debian
      - libgl1-mesa-glx
      - libpulse0
      - libgomp1
      - yad
      - libslang2
      - fluid-soundfont-gm
      - libglu1-mesa
      - kdialog
    after:
      - qt5
  qt5:
    source: .
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all

layout:
  /usr/share/games/doom: # to locate the .pk3 files
    bind: $SNAP/share/games/doom
  /usr/share/doom/soundfonts: # to locate the soundfonts
    bind: $SNAP/usr/share/sounds/sf2
